// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDHh08-_WT6I3DcO9of2xqEdM96gmUcM',
    appId: '1:490861874939:web:5afd6a12ba82beb4d9ea5e',
    messagingSenderId: '490861874939',
    projectId: 'notification-71e0f',
    authDomain: 'notification-71e0f.firebaseapp.com',
    storageBucket: 'notification-71e0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCra3cm4JZVK58a-hSDI0lOjKE4CRTHxtc',
    appId: '1:490861874939:android:1eaf27f97dacac74d9ea5e',
    messagingSenderId: '490861874939',
    projectId: 'notification-71e0f',
    storageBucket: 'notification-71e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_BFaTOOH5HVJFePibePqpMc5Bn2gnNmU',
    appId: '1:490861874939:ios:31ff9ef61778ec59d9ea5e',
    messagingSenderId: '490861874939',
    projectId: 'notification-71e0f',
    storageBucket: 'notification-71e0f.appspot.com',
    iosBundleId: 'com.example.shopvegetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_BFaTOOH5HVJFePibePqpMc5Bn2gnNmU',
    appId: '1:490861874939:ios:31ff9ef61778ec59d9ea5e',
    messagingSenderId: '490861874939',
    projectId: 'notification-71e0f',
    storageBucket: 'notification-71e0f.appspot.com',
    iosBundleId: 'com.example.shopvegetable',
  );
}
